### PR TITLE
kexec-hardboot patch for multirom.

### PR DESCRIPTION
**Pull request by vijaykrp**
These changes are required to support multirom on falcon.

### CODE REVIEW

**Comment by vijaykrp** [comment]
The corresponding thread is at http://forum.xda-developers.com/moto-g/development/mod-multirom-v27-testing-t2852897

**Comment by Alberto97** [comment]
Sorry, but you have to push your changes into CyanogenMod Gerrit, they don't accept  Github pull requests :(

**Comment by rabih** [comment]
Submit to gerrit, no pull requests allowed.

**Comment by cm-gerrit** [comment]
Hi there;

This is an automated reply, to let you know CyanogenMod doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at http://review.cyanogenmod.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.cyanogenmod.org/wiki/Howto:_Gerrit

Thanks!

**Pull request closed without merging**
